mod.id = "bedrock-miner"
mod.name = "Bedrock-Miner"
mod.group = "com.github.lxyan2333.bedrockminer"
mod.version = "2.0.6"

deps.fabric_loader = "0.19.3"
deps.fabric_kotlin = "1.13.12+kotlin.2.4.0"

["1.16.5"]
mod.mc_compat = "1.16.5"
mod.mc_releases = ["1.16.5"]

deps.fabric_api = "0.42.0+1.16"
deps.malilib_mc = "1.16.5"
deps.malilib = "0.10.0-dev.21+arne.9"
deps.mod_menu = "2.0.2"

["1.17.1"]
mod.mc_compat = "1.17.1"
mod.mc_releases = ["1.17.1"]

deps.fabric_api = "0.46.1+1.17"
deps.malilib_mc = "1.17.1"
deps.malilib = "0.10.0-dev.23"
deps.mod_menu = "2.0.2"

["1.18.2"]
mod.mc_compat = "1.18.2"
mod.mc_releases = ["1.18.2"]

deps.fabric_api = "0.77.0+1.18.2"
deps.malilib_mc = "1.18.2"
deps.malilib = "0.12.0"
deps.mod_menu = "3.1.0"

["1.19.2"]
mod.mc_compat = "1.19.2"
mod.mc_releases = ["1.19.2"]

deps.fabric_api = "0.77.0+1.19.2"
deps.malilib_mc = "1.19.2"
deps.malilib = "0.13.0"
deps.mod_menu = "4.0.6"

["1.19.4"]
mod.mc_compat = "1.19.4"
mod.mc_releases = ["1.19.4"]

deps.fabric_api = "0.87.2+1.19.4"
deps.malilib_mc = "1.19.4"
deps.malilib = "0.15.5-alpha.1"
deps.mod_menu = "6.3.1"

["1.20.1"]
mod.mc_compat = "1.20.1"
mod.mc_releases = ["1.20.1"]

deps.fabric_api = "0.92.9+1.20.1"
deps.malilib_mc = "1.20.1"
deps.malilib = "0.16.4-alpha.1"
deps.mod_menu = "7.2.2"

["1.20.6"]
mod.mc_compat = "1.20.6"
mod.mc_releases = ["1.20.6"]

deps.fabric_api = "0.100.8+1.20.6"
deps.malilib_mc = "1.20.6"
deps.malilib = "0.19.2"
deps.mod_menu = "10.0.0"

["1.21.1"]
mod.mc_compat = "1.21.1"
mod.mc_releases = ["1.21.1"]

deps.fabric_api = "0.116.13+1.21.1"
deps.malilib_mc = "1.21"
deps.malilib = "0.21.10"
deps.mod_menu = "11.0.1"

["1.21.11"]
mod.mc_compat = "1.21.11"
mod.mc_releases = ["1.21.11"]

deps.fabric_api = "0.141.4+1.21.11"
deps.malilib_mc = "1.21.11"
deps.malilib = "0.27.13"
deps.mod_menu = "15.0.0-beta.3"

["26.2"]
mod.mc_compat = "26.2"
mod.mc_releases = ["26.2"]

deps.fabric_api = "0.154.0+26.2"
deps.malilib_mc = "26.2"
deps.malilib = "0.29.2"
deps.mod_menu = "19.0.0-alpha.1"
