# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  get-versions:
    runs-on: ubuntu-24.04
    outputs:
      versions: ${{ steps.parse.outputs.versions }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: parse versions from versions.json
        id: parse
        run: |
          VERSIONS=$(jq -c '.versions' versions.json)
          echo "versions=$VERSIONS" >> "$GITHUB_OUTPUT"

  build:
    needs: get-versions
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.get-versions.outputs.versions) }}
    env:
      CI_VERSION: ${{ matrix.version }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '26'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Download dependencies (with retry)
        run: |
          for i in {1..15}; do
            echo "Attempt $i to download dependencies..."
            ./gradlew dependencies --no-daemon && break || sleep 15
          done
      - name: build
        run: ./gradlew :${{ matrix.version }}:build
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts-${{ matrix.version }}
          path: versions/${{ matrix.version }}/build/libs/*.jar
